import type { Metadata } from 'next';
import { Theme, Flex, Heading, Button } from '@radix-ui/themes';

import '@radix-ui/themes/styles.css';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Movie Explorer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <section>
            <header>
              <Flex className="m-8 border-2 border-solid p-8 rounded-2xl shadow-md" direction="column" align="center">
                <Heading as="h1">Movie Explorer</Heading>
              </Flex>
              <Flex className="m-8">
              <Link className='text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700' href='/movies'>New Search</Link>
              <Link className='text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700' href='/movies/watchlist'>My Watch List</Link>
              </Flex>
            </header>
            <main className="m-8 rounded-md"> 
              {children}
            </main>
          </section>
        </Theme>
      </body>
    </html>
  );
}
